version: '1'

env:
  ## container
  REGISTRY_PREFIX: europe-docker.pkg.dev/ceiba-platform-cicd/
  CONTAINER_NAME: tools/kubespecdev


tasks:
  install:
    desc: Install exact dependencies from lockfile
    cmds:
      - npm ci

  lint:
    desc: Run Astro + TypeScript checks
    cmds:
      - npm run astro check

  build-image:
    desc: Build container image
    requires:
      vars: [ REGISTRY_PREFIX, CONTAINER_NAME, CONTAINER_TAG, GITHUB_TOKEN ]
    cmds:
      - |
        docker build . \
        -t $(REGISTRY_PREFIX)$(CONTAINER_NAME):$(CONTAINER_TAG) \
        --build-arg GITHUB_TOKEN=$(GITHUBH_TOKEN)

  push:
    desc: Push container image to Container Registry
    requires:
      vars: [ REGISTRY_PREFIX, CONTAINER_NAME, CONTAINER_TAG ]
    cmds:
      - docker push $(REGISTRY_PREFIX)$(CONTAINER_NAME):$(CONTAINER_TAG)
