version: '3'

env:
  ## container
  REGISTRY_PREFIX: europe-docker.pkg.dev/ceiba-platform-cicd/
  CONTAINER_NAME: tools/kubespec-cicd


tasks:
  install:
    desc: Install exact dependencies from lockfile
    cmds:
      - npm ci

  download:
    desc: Download CRDs (requires GH_TOKEN)
    requires:
      vars: [GH_TOKEN]
    cmds:
      - npm run download

  build:
    desc: Build static site (dist/)
    cmds:
      - npm run build

  lint:
    desc: Run Astro + TypeScript checks
    cmds:
      - npm run astro check

  build-image:
    desc: Build container image
    requires:
      vars: [ REGISTRY_PREFIX, CONTAINER_NAME, CONTAINER_TAG, GH_TOKEN ]
    cmds:
      - |
        docker build . \
        -t $(REGISTRY_PREFIX)$(CONTAINER_NAME):$(CONTAINER_TAG) \
        --build-arg GH_TOKEN=$(GH_TOKEN)

  push:
    desc: Push container image to Container Registry
    requires:
      vars: [ REGISTRY_PREFIX, CONTAINER_NAME, CONTAINER_TAG ]
    cmds:
      - docker push $(REGISTRY_PREFIX)$(CONTAINER_NAME):$(CONTAINER_TAG)
