version: '3'

env:
  CONTAINER_REGISTRY: europe-docker.pkg.dev/ceiba-platform-cicd/
  CONTAINER_NAME: tools/kubespecdev

tasks:
  install:
    desc: Install exact dependencies from lockfile
    cmds:
      - npm ci

  download:
    desc: Download projects
    requires:
      vars: [ GITHUB_TOKEN ]
    cmds:
      - npm run download

  build:
    desc: Build pages
    cmds:
      - npm run build

  lint:
    desc: Run checks
    cmds:
      - npm run astro check

  build-container:
    desc: Build container image
    requires:
      vars: [ CONTAINER_REGISTRY, CONTAINER_NAME, CONTAINER_TAG, GITHUB_TOKEN ]
    cmds:
      - |
        docker build . \
        -t $(CONTAINER_REGISTRY)$(CONTAINER_NAME):$(CONTAINER_TAG) \
        --build-arg GITHUB_TOKEN=$(GITHUB_TOKEN)

  push-to-registry:
    desc: Push container image to registry
    requires:
      vars: [ CONTAINER_REGISTRY, CONTAINER_NAME, CONTAINER_TAG ]
    cmds:
      - docker push $(CONTAINER_REGISTRY)$(CONTAINER_NAME):$(CONTAINER_TAG)
